app:
    build: .
    environment:
        REALM: prod
        REDIS_URL: "//redis:6379"
    links:
        - redis
    volumes:
        - ./caliper-log-events:/requests
    ports:
        - "8040:8000"

redis:
    image: redis
